dist: xenial  # trusty's version of glib is too old
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
addons:
  apt:
    packages:
    - libpoppler-glib-dev
    - libpoppler-dev
    - libcairo2-dev
    - libglib2.0-dev
