[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
name = "popplertest"
version = "0.1.0"

[dependencies]
cairo-rs = "0.3.0"
cairo-sys-rs = "0.5.0"
glib = "0.4.0"
glib-sys = "0.5.0"
gobject-sys = "0.5.0"
